#Harald
version: '3.0'
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: "swagger"
    volumes:
      - ./Swagger.json:/Swagger.json
    environment:
      SWAGGER_JSON: /Swagger.json
    ports:
      - "8081:8080"
